### ISSUE TITLE
support odoo 10

### ISSUE THREAD

**Issue by gurneyalex** [camptocamp/marabunta#10]
Currently, if I want to install modules on v10, I get:

```
|> version 10.1.0: installation / upgrade of addons
|> version 10.1.0: odoo.py --workers=0 --stop-after-init -i purchase,account,mrp_maintenance,stock_barcode,web_studio,fleet,l10n_fr,account_accountant,document,sale_stock
Traceback (most recent call last):
  File "/usr/local/bin/marabunta", line 11, in <module>
    sys.exit(main())
  File "/usr/local/lib/python2.7/dist-packages/marabunta/core.py", line 60, in main
    migrate(config)
  File "/usr/local/lib/python2.7/dist-packages/marabunta/core.py", line 41, in migrate
    runner.perform()
  File "/usr/local/lib/python2.7/dist-packages/marabunta/runner.py", line 86, in perform
    VersionRunner(self, version).perform()
  File "/usr/local/lib/python2.7/dist-packages/marabunta/runner.py", line 150, in perform
    self.perform_addons()
  File "/usr/local/lib/python2.7/dist-packages/marabunta/runner.py", line 178, in perform_addons
    operation.execute(self.log)
  File "/usr/local/lib/python2.7/dist-packages/marabunta/model.py", line 259, in execute
    self._execute(log, interactive=sys.stdout.isatty())
  File "/usr/local/lib/python2.7/dist-packages/marabunta/model.py", line 215, in _execute
    timeout=None,
  File "/usr/local/lib/python2.7/dist-packages/pexpect/pty_spawn.py", line 197, in __init__
    self._spawn(command, args, preexec_fn, dimensions)
  File "/usr/local/lib/python2.7/dist-packages/pexpect/pty_spawn.py", line 270, in _spawn
    'executable: %s.' % self.command)
pexpect.exceptions.ExceptionPexpect: The command was not found or was not executable: odoo.py.
```

**Comment by gurneyalex** [comment]
workaround: use:

    install_command: odoo

instead of:

    install_command: odoo.py

in `migration.yml`

**Comment by gurneyalex** [comment]
ping @vrenaville

**Comment by guewen** [comment]
The workaround is correct. The latest release (https://github.com/camptocamp/marabunta/releases/tag/0.5.0) which is the release used in docker-odoo-project 1.6.0 (https://github.com/camptocamp/docker-odoo-project/releases/tag/1.6.0) now uses `odoo` by default instead of `odoo.py` though.

In your Dockerfile, you'd want to use `FROM camptocamp/odoo-project:10.0-1.6.0`. 

Note that `FROM camptocamp/odoo-project:9.0-1.6.0` supports both `odoo.py` and `odoo` so you don't need to set `install_command: odoo.py` for odoo 9.0 instances.
