### ISSUE TITLE
Custom port not converted to integer

### ISSUE THREAD

**Issue by oerp-odoo** [camptocamp/marabunta#66]
If you pass custom `WEB_PORT`, (not 8069 default), it will throw this error:

```python
Exception in thread Thread-1:
Traceback (most recent call last):
  File "/usr/lib/python3.9/threading.py", line 954, in _bootstrap_inner
    self.run()
  File "/opt/odoo/venv/lib/python3.9/site-packages/marabunta/core.py", line 100, in run
    self.app.serve()
  File "/opt/odoo/venv/lib/python3.9/site-packages/marabunta/web.py", line 30, in serve
    run_simple(self.host, self.port, self)
  File "/opt/odoo/venv/lib/python3.9/site-packages/werkzeug/serving.py", line 923, in run_simple
    raise TypeError("port must be an integer")
TypeError: port must be an integer
```

**Comment by yvaucher** [comment]
Solved by #69
